# Generated by Django 4.2.5 on 2023-12-14 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discurso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retroalimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claridad', models.TextField()),
                ('coherencia', models.TextField()),
                ('muletillas', models.TextField()),
                ('redundancia', models.TextField()),
                ('sugerencia_mejora', models.TextField()),
                ('discurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discurso.discurso')),
            ],
        ),
    ]
