# Generated by Django 4.2.5 on 2023-12-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discurso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discurso',
            name='uid',
            field=models.CharField(max_length=255),
        ),
    ]
